low_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Dylib
        run: |
          xcrun -sdk iphoneos clang++ -arch arm64 -shared -std=c++17 \
          -fobjc-arc
