name: Build Dylib
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Dylib
        run: |
          xcrun -sdk iphoneos clang++ -arch arm64 -shared -std=c++17 \
          -fobjc-arc -framework UIKit -framework Foundation -framework CoreGraphics \
          -Wno-deprecated-declarations -Wno-arc-performSelector-leaks \
          -O2 mod.mm -o libBaldi.dylib
      - uses: actions/upload-artifact@v4
        with:
          name: libBaldi
          path: libBaldi.dylib
